---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-organization:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Organization Module Validation
    with:
      working-directory: examples/basic

  validate-delegation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Delegation Module Validation
    with:
      working-directory: modules/delegation

  validate-delegation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Service Quotas Module Validation
    with:
      working-directory: modules/service_quotas
